language: python
python:
  - 2.7
  - 3.4

sudo: false

# Setup anaconda following http://conda.pydata.org/docs/travis.html#the-travis-yml-file
before_install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # For tests with plot instructions
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# Install packages
install:
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy scipy matplotlib nose
  - source activate test-environment
  - pip install -e "git+https://github.com/z4r/python-coveralls.git#egg=pycoveralls"
  - pip install nose-cov
  - pip install .

# Run test
script:
  - nosetests --with-cov --cov=multishake --cov-config=.coveragerc --logging-level=DEBUG

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
